Update GitHub Actions workflow

diff --git a/.github/workflows/lambda.yml b/.github/workflows/lambda.yml
--- a/.github/workflows/lambda.yml
+++ b/.github/workflows/lambda.yml
@@ -10,7 +10,7 @@ on:
 jobs:
   deploy-lambda: # name of our job
     runs-on: ubuntu-latest # Sets or specifies the runner
-    stops: 
+    steps: 
       - uses: actions/checkout@v2
     
       - name: Set Up Python # Setups our python env
@@ -19,20 +19,25 @@ jobs:
           python-version: '3.12'
 
       - name: Install Dependencies # Installs any packages
-        runs: |
+        run: |
           python -m pip install --upgrade pip
           pip install -r lambda/requirements.txt -t lambda/
 
-      - name: Configure AWS Creds  # Sets up our AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+      - name: Configure AWS Credentials # Sets up our AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
         with: 
-          aws-access-key-id:  ${{ secrets.AKIAQXUIXT3JSG2MPPSD}}
-          aws-access-secret-key: ${{ secrets.eAcuUxQDA49Uc/1nugBsDMNpGkIimArfCwBtOusE}}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ca-central-1
+
+      - name: Ensure lambda directory exists
+        run: |
+          if [ ! -d "lambda" ]; then echo "Lambda directory not found!"; exit 1; fi
       
-      - name: Deploy Lambda Function #Zips lambda directory
+      - name: Deploy Lambda Function  # Zips lambda directory
         run: |
           cd lambda
           zip -r lambda.zip .
-          aws lambda update-function-code --function-name my-test-cicd-lambda  --zip-file fileb://lambda.zip
-
+          mv lambda.zip .
+          cd ..
+          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
